name: .NET

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Pack
      run: nuget pack Prognetdev.Templates.Console.nuspec -OutputDirectory out

    - name: Setup .NET for Push
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        source-url: https://api.nuget.org/v3/index.json

    - name: Push
      env:
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push ./out/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json