name: .NET

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} # If needed for dotnet restore or other commands

      - name: Pack
        run: nuget pack Prognetdev.Templates.Console.nuspec -OutputDirectory out
        
      - name: Push
        run: dotnet nuget push "./out/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
